### ISSUE TITLE
Pending and Holding Count

### ISSUE THREAD

**Issue by Dvent1123** [Brehtyn/Business-Service-Program#30]
Still am unsure as to where to put the pending and holding count. In the header.ejs file at line 182 I see a post_count but am uncertain if that is total posts or only pending or only holding posts. It'd be cool if Brentyn saw this and could comment in which file and what line he wants the pending and holding count

**Comment by Dvent1123** [comment]
I didn't know I could assign stuff but now I do >:)

**Comment by Brehtyn** [comment]
lets do lines 6&46 for the pending and holding respectively in the main index.ejs

labeled by type_NUMBER

**Comment by Brehtyn** [comment]
@Dvent1123 silly me heres your calling

**Comment by Dvent1123** [comment]
Amazing Work
