### ISSUE TITLE
Individual User Styling

### ISSUE THREAD

**Issue by Dvent1123** [Brehtyn/Business-Service-Program#33]
Need to style the page for the individual user. users/show specifically

**Comment by Brehtyn** [comment]
@Dvent1123 is this user page accessible by the dropdown sufficient?

**Comment by Dvent1123** [comment]
I'm not sure if you're saying it will only be referenced by the dropdown? When  you click on the users tab in the header I believe this is the view that appears and isn't styled and that is all I know
